{% set name = "biorbd-viz" %}
{% set version = "1.2.5" %}
{% set build_num = 0 %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/pyomeca/{{ name }}/archive/Release_{{ version }}.tar.gz
  sha256: 3f2409af0899eff717196c2a77526ae3f3a3f414e6c045a81554bf790a1f62ae
  
build:
  number: {{ build_num }}
  skip: true  # [py<36]
  skip: true  # [backend == "casadi" and py>37]
  script: "{{ PYTHON }} -m pip install . -vv"
  string: py{{ py }}_{{ backend }}_h{{ PKG_HASH }}_{{ build_num }}
  track_features:
    - casadi  # [backend == "casadi"]

requirements:
  host:
    - python
    - pip
  run:
    - python
    - biorbd =*=casadi*  # [backend == "casadi"]
    - biorbd  # [backend == "eigen"]
    - vtk
    - pyqt
    - pyomeca

test:
  imports:
    - BiorbdViz  # [not linux]

about:
  home: http://github.com/pyomeca/biorbd-viz
  license: Apache-2.0
  license_file: LICENSE
  summary: 'Biorbd visualization toolkit'
  description: |
    Biorbd visualization toolkit 
  doc_url: https://github.com/{{ name }}/{{ name }}
  dev_url: https://github.com/{{ name }}/{{ name }}

extra:
  recipe-maintainers:
    - pariterre
