{% set name = "biorbd-viz" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/pyomeca/{{ name }}/archive/Release_{{ version }}.tar.gz
  sha256: 9e8aef6dce5f390605f46507cb1222ce5147b9d9dd51fdd2cdda4fd95062630b
  
build:
  skip: True  # [py<35]
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - biorbd
    - vtk
    - pyqt
    - pyomeca

test:
  commands:
    - xvfb-run python -c "import BiorbdViz"  # [linux]
  imports:
    - BiorbdViz  # [not linux]

about:
  home: http://github.com/pyomeca/biorbd-viz
  license: Apache-2.0
  license_file: LICENSE
  summary: 'Biorbd visualization toolkit'
  description: |
    Biorbd visualization toolkit 
  doc_url: https://github.com/{{ name }}/{{ name }}
  dev_url: https://github.com/{{ name }}/{{ name }}

extra:
  recipe-maintainers:
    - pariterre
