travis:
  secure:
    BINSTAR_TOKEN: H9gia9EpGu4A/Bkbgp0Rd7nlf2sKLlKvfkhIsatl95h2zlnVQPi9wJmC8TzIGGplQFG4N86jeMXuWdC4GvVCX2kWHTD6o2bZS0kt77062bYe0y8MRW9c1ejT7/H9mE6KkIMi7x98aaytY3V9ynIxrbm0xL3FIjtriuondyE90MJUfCpXuz28TANciwUU0MBbZ6NQTCDS2v49hiFgi2pmqOFF1/MI7Z9gloPEm3WmvAmMeBvwWshGaW5FNlyiE8+agcgymgTA2yKnSTInI9l/808Wb/mwzje83HxiRn6aqRfPbb4yqvL7WV/xxB0htXqptls3RdZSHRgIRYGg/vs3UhvV/1biGl6Rmp9hNqlL+8CrDfwdMsWm3tK9VoSaJFG9Le2P4AG7TPUU1srCVPNwKFdHGbciOhjy+JdrhDtsiUurx/3ufmPo/RJba8OlJWKjV4IZtizjiISNJCT8zjCGjkrID9j4Oi3hfEQ3faCXz2GCZa+JYLqpG+ZkmelmTPrsl/pAOvJJo+a86mTLnm/TLQSDlECMH5nTib4JMqychWHoKws3xIWLXx6RxRzPEjjx6BTOIxy/QkNV9FoL7gsYxMBDQ24a9d1OdXLfk6t4k95N3MQz3GZ0ZdsM3MWFDB/PJIN+FJ5TZ60agTDz4T+c52bkSLEJznCz9sc3c9olvkA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
conda_forge_output_validation: true
